name: Testing main pipeline

# Triggering event
on:
  push:
    branches:
      - main

# Jobs -> do these
jobs:
  simple_test_pipeline:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
      
      - name: Install dependencies
        run: npm install

      - name: Run frontend tests
        run: npm run test
        
